### ISSUE TITLE
[REQUEST]: Convert to a perpetual unified log

### ISSUE THREAD

**Issue by goodnightkara** [nikkisaurus/GuildBankSnapshots#10]
### Describe what you want to be implemented?

Convert to a perpetual unified log. Compare new snapshots with previous ones and add the new unique entries to the perpetual unified log. The unified log will enhance the usefulness of your analytic options (gold deposits and withdrawals by specific Characters over time, for example.)

### Explain why you want this feature implemented.

The current state of the addon isolates each snapshot as its own entity. Using the analytical tools on each snapshot independently is only as useful as the log is long. By converting to a unified log, the ability to watch behavioral trends over time will be much simpler, and therefore the usefulness of the addon will increase.

**Comment by nikkisaurus** [comment]
This is something that I've attempted to do, but it has a lot of issues. The main problem is that there are no unique identifiers for each transaction, so I have to try to programmatically determine which entries are duplicate, which isn't exactly an easy task, especially if you have say a whole log with what appears to be the same transaction over and over again.

For example, say you deposit multiple pets; battle pets all show up as pet cages so the transactions will look the same. Because of that it can be hard to tell between logs if some things are duplicate or unique transactions.

I will not say I will never have something like this, but right now I am still wracking my brain for solutions to this major problem.

**Comment by goodnightkara** [comment]
Thanks for the response. If Blizzard doesn't expose transaction UIDs, then yeah I'd say that it's not really possible to offer this functionality **and** claim the data (transactions) are factual and complete.

You could consider making an attempt at this with the financial log. Typically, money transactions are for unique amounts, so it may be easier to discern which entries the addon has already seen and which ones are new.

Again, thanks for reviewing this and responding. Good luck with the addon!

**Comment by JerbAcuch** [comment]
Would this be possible to do by tracking each item by time with a delta and then adjusting them down as scans happens and the dates and times adjust?  Depending on the time between scans, it should give you a decent Window.  That, plus overlaps should help, no?

There would be a method to confuse it by withdrawing in a pattern after cycling the page, but then the dates should be off and it would see a "---- GAP DETECTED---".  If a time is > 2 hours, you know you couldn't have missed something, if the last transaction is known and syncs up, you MIGHT no something based on the delta, but overlap is needed to be sure of anything.

The only other part that would be needed here is addon message that would help keep all of them discovered as well as reduce the delta and get more overlaps.  This should be restricted to only "top ranks" to prevent pollution and by default only the guild master.

Database when the last check was over an hour would be:
estimated time, delta, user, item, action

If you check back 10 minutes later and a time shifted an hour, you know it's now +/- 5 minutes from the average time of now to last check.

If someone else logged on and it is lower you can just "use that value" or now actually do the intersection of the two times and deltas to find a new delta [latest - delta_1 vs earliest + delta_2]: delta_2-delta_1.

The math seems right, except the last line may be way off but that should be discoverable through trial and error.
