### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ayeager77** [nikkisaurus/GuildBankSnapshots#13]
### Interface Version

10.0.0

### AddOn Version

v3.4.5-wrath

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

Installed, opened Guild Bank, and used /scan command. Received "GuildBankSnapshots: Please open your guild bank frame and try again." Turned off all addons except Guild Bank Snapshots and received same message. I am in a guild; I am an officer with permissions. I logged into my banker alt, since I am the GM and only member. Again, turned off all addons except GBS, verified I had Load out of Date enabled, and got the same results.  I do not know what else to try, since there were no bug popups or errors.

### Please supply a copy of your saved variables.

[GBS.txt](https://github.com/nikkisaurus/GuildBankSnapshots/files/10502460/GBS.txt)

**Comment by JerbAcuch** [comment]
GuildBankSnapshots.lua

Line 20, Change to:
`    if select(4, GetBuildInfo()) >=0 then`

**Comment by nikkisaurus** [comment]
Sorry it's taken so long to address this. The guild I was in for classic to test this addon kicked me out and I don't actively play classic. But, I have a friend that may be able to get me into a guild tomorrow.

@JerbAcuch thank you for the reply. I did log into classic and see that EventUtil is implemented in classic now (I don't think it was before and I really don't keep up with anything classic related), so assuming this is the problem, I appreciate that you've given me somewhere to start troubleshooting and it will be a quick, easy fix if that's the case.
