### ISSUE TITLE
[Bug]: LUA Error in 11.02 = SOLVED

### ISSUE THREAD

**Issue by zalidthebur** [nikkisaurus/GuildBankSnapshots#15]
### Interface Version

11.0.2

### AddOn Version

3.5.2

### Have you replicated this error without any other addons loaded?

No

### What steps did you take leading up to this issue?

Open guild bank and error (addon still worked though):

1x ...aceGuildBankSnapshots/GuildBankSnapshots.lua:24: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@GuildBankSnapshots/GuildBankSnapshots.lua"]:24: in function <...aceGuildBankSnapshots/GuildBankSnapshots.lua:20>
[string "@Blizzard_SharedXML/EventUtil.lua"]:74: in function <Blizzard_SharedXML/EventUtil.lua:66>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua"]:9: in function <...ns/Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua:8>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:485: in function `loadFunc'
[string "@Blizzard_UIPanels_Game/Shared/PlayerInteractionFrameManager.lua"]:194: in function <...Panels_Game/Shared/PlayerInteractionFrameManager.lua:187>
[string "=[C]"]: in function `ShowFrame'
[string "@Blizzard_UIPanels_Game/Shared/PlayerInteractionFrameManager.lua"]:240: in function <...Panels_Game/Shared/PlayerInteractionFrameManager.lua:237>

Locals:
(*temporary) = nil
(*temporary) = "ArkInventory"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
addon = <table> {
 modules = <table> {
 }
 baseName = "GuildBankSnapshots"
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 name = "GuildBankSnapshots"
 orderedModules = <table> {
 }
 defaultModuleState = true
 hooks = <table> {
 }
}
private = <table> {
 unitsToSeconds = <table> {
 }
 db = <table> {
 }
 frame = <table> {
 }
 defaults = <table> {
 }
 selectedScans = <table> {
 }

AND

1x ...aceGuildBankSnapshots/GuildBankSnapshots.lua:27: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@GuildBankSnapshots/GuildBankSnapshots.lua"]:27: in function <...aceGuildBankSnapshots/GuildBankSnapshots.lua:20>
[string "@Blizzard_SharedXML/EventUtil.lua"]:74: in function <Blizzard_SharedXML/EventUtil.lua:66>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua"]:9: in function <...ns/Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua:8>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:485: in function `loadFunc'
[string "@Blizzard_UIPanels_Game/Shared/PlayerInteractionFrameManager.lua"]:194: in function <...Panels_Game/Shared/PlayerInteractionFrameManager.lua:187>
[string "=[C]"]: in function `ShowFrame'
[string "@Blizzard_UIPanels_Game/Shared/PlayerInteractionFrameManager.lua"]:240: in function <...Panels_Game/Shared/PlayerInteractionFrameManager.lua:237>

Locals:
(*temporary) = nil
(*temporary) = "Bagnon"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
addon = <table> {
 modules = <table> {
 }
 baseName = "GuildBankSnapshots"
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 name = "GuildBankSnapshots"
 orderedModules = <table> {
 }
 defaultModuleState = true
 hooks = <table> {
 }
}
private = <table> {
 unitsToSeconds = <table> {
 }
 db = <table> {
 }
 frame = <table> {
 }
 defaults = <table> {
 }
 selectedScans = <table> {
 }
}

SOLVED:
GuildBankSnapshots.lua

line 24 was
if IsAddOnLoaded("ArkInventory") and _G["ARKINV_Frame4"] then
TO
if C_AddOns.IsAddOnLoaded("ArkInventory") and _G["ARKINV_Frame4"] then

line 27 was
elseif IsAddOnLoaded("Bagnon") and _G["BagnonBankFrame1"] then
TO
elseif C_AddOns.IsAddOnLoaded("Bagnon") and _G["BagnonBankFrame1"] then

**Comment by nikkisaurus** [comment]
I should just need to go in and update the call to the IsAddonLoaded function. I just have been swamped with moving at the moment.

**Comment by zalidthebur** [comment]
No worries. At least it was an easy fix and I'm sure anyone could do the changes if they wanted to.
