### ISSUE TITLE
[REQUEST]: Possibility to change /gbs UI command

### ISSUE THREAD

**Issue by keflatbn** [nikkisaurus/GuildBankSnapshots#16]
### Describe what you want to be implemented?

Hi, first a big thanks for this addon, its been superimportant now with all the problems of items being lost in guildbank.

I'm currently also using an addon called Guild Bank Sort, and it uses the same /GBS as GuildBankSnapshot

I see you already have settings for the /scan command to use other alternatives, could you please add an alterantive to the /gbs too? Example /gbsort for example

### Explain why you want this feature implemented.

Since /gbs is used by two addons I have and this addon already have setting options to change /-commands, then I thought it maybe could be implemented there

### Describe any alternatives you've considered.

I disable the addon GuildBankSort when I want to check the logs or export, but it is tidious since I have guilds on several servers and need to disable via the realm setting

**Comment by nikkisaurus** [comment]
I can add an alternate command. I could do maybe /gbsnaps to keep it kind of short, as opposed to /guildbanksnapshots, just in case it's something you ever type.

**Comment by keflatbn** [comment]
Hi, I actually meant to suggest /gbsnaps, but wrote /gbsort :) 
Anyways as long as it has an alternative to /gbs then I'm totally fine!
Thanks for a quick reply!

**Comment by keflatbn** [comment]
Just saw the update, works like a charm, thanks for the superfast fix! <3

**Comment by nikkisaurus** [comment]
I meant to comment here to let you know, but was busy. Glad to help!
