### ISSUE TITLE
/gbs command not working

### ISSUE THREAD

**Issue by selenara** [nikkisaurus/GuildBankSnapshots#3]
/gbs does not open main window.
also /gbs scan starts scanning but does not show main window.

Because of this I can't access addon data.

**Comment by niketa-wow** [comment]
Is there a Lua error?

**Comment by niketa-wow** [comment]
Should be fixed with latest update, but if it's not, reopen this issue with more information please. Thanks!

https://github.com/niketa-wow/guildbanksnapshots/releases/tag/v2.0.8
