### ISSUE TITLE
[BUG] LUA error with Latest update

### ISSUE THREAD

**Issue by zalidthebur** [nikkisaurus/GuildBankSnapshots#4]
Date: 2021-07-22 18:56:46
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GuildBankSnapshots\Settings.lua line 198:
   unexpected symbol near '['
Debug:
   [string "=[C]"]: ?
Locals:

AddOns:
...
  GuildBankSnapshots, vv2.0.7
...

**Comment by niketa-wow** [comment]
Should be fixed in latest update.
https://github.com/niketa-wow/guildbanksnapshots/releases/tag/v2.0.8
