### ISSUE TITLE
`[BUG] After clicking Export Pending, nothing happens

### ISSUE THREAD

**Issue by selenara** [nikkisaurus/GuildBankSnapshots#5]
**Describe the bug**
I cannot export my transactions. I press Export Pending (after I populated the box "Pending Snapshots". Nothing happens.

**Client**
Wow 9.1

**To Reproduce**
1. Open guild bank
2. Type /gbs scan
3. Click Manage
4. Select Guild from drop down menu
5. Left click the the snapshot/s from Available Snapshots box
6. The Pending Snapshots box gets populated with snapshots
7. Left Click Export Pending

**Expected behavior**
The box on the right to Pending Snapshots does not get populated with text.

**Screenshots**

**Additional context**

**Comment by zalidthebur** [comment]
I just tried it to see and when I clock export I get the following LUA error. Maybe you don't have error showing enabled, or an addon to show them ?
Date: 2021-07-23 20:09:55
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\GuildBankSnapshots\Manage.lua line 412:
   attempt to concatenate local 'delimiter' (a nil value)
Debug:
   [string "@TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [string "=[C]"]: ?
   [string "@GuildBankSnapshots\Manage.lua"]:412:
      GuildBankSnapshots\Manage.lua:378
Locals:
errMsg = "Interface\AddOns\GuildBankSnapshots\Manage.lua:412: attempt to concatenate local 'delimiter' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:609
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
...
  GuildBankSnapshots, vv2.0.8
...

**Comment by selenara** [comment]
Indeed I have disabled lua errors in-game. so is this a bug?

**Comment by niketa-wow** [comment]
If you are comfortable making a change, change line 380 of Manage.lua from

local delimiter = db.settings.exportDelimiter

to

local delimiter = db.settings.exportDelimiter or ","

If more issues arise after this let me know. If it's good I can push a change from away from home. Otherwise it won't be until I get home in 8 hours before I can troubleshoot.

**Comment by selenara** [comment]
Ty! Indeed it works now. I have saved a .csv file as instructed, but this is how it looks. I'm not sure if it's intended or not, but for me I find this unreadable. These are a few lines from the file.

guildName2snapshotDate2tabName2transactionType2name2itemName2itemLevel2itemMoneyCount2moveTabName12moveTabName22timeSince2transactionDate2line
Elysion-Ravencrest [A]2Jul 24, 2021 (01:52)2Cooking2withdraw2Elysionbank2Shadowy Shank22200222< an hour ago2approx. 1 AM on 7/24/212Elysionbank withdrew [Shadowy Shank] x 200   ( < an hour ago )
Elysion-Ravencrest [A]2Jul 24, 2021 (01:52)2Cooking2withdraw2Elysionbank2Raw Seraphic Wing22200222< an hour ago2approx. 1 AM on 7/24/212Elysionbank withdrew [Raw Seraphic Wing] x 200   ( < an hour ago )
Elysion-Ravencrest [A]2Jul 24, 2021 (01:52)2Cooking2withdraw2Elysionbank2Raw Seraphic Wing22200222< an hour ago2approx. 1 AM on 7/24/212Elysionbank withdrew [Raw Seraphic Wing] x 200   ( < an hour ago )
Elysion-Ravencrest [A]2Jul 24, 2021 (01:52)2Cooking2withdraw2Elysionbank2Shadowy Shank22200222< an hour ago2approx. 1 AM on 7/24/212Elysionbank withdrew [Shadowy Shank] x 200   ( < an hour ago )
Elysion-Ravencrest [A]2Jul 24, 2021 (01:52)2Cooking2withdraw2Elysionbank2Pocked Bonefish22200222< an hour ago2approx. 1 AM on 7/24/212Elysionbank withdrew [Pocked Bonefish] x 200   ( < an hour ago )
Elysion-Ravencrest [A]2Jul 24, 2021 (01:52)2Cooking2withdraw2Elysionbank2Pocked Bonefish22200222< an hour ago2approx. 1 AM on 7/24/212Elysionbank withdrew [Pocked Bonefish] x 200   ( < an hour ago )
Elysion-Ravencrest [A]2Jul 24, 2021 (01:52)2Cooking2withdraw2Elysionbank2Pocked Bonefish22200222< an hour ago2approx. 1 AM on 7/24/212Elysionbank withdrew [Pocked Bonefish] x 200   ( < an hour ago )

**Comment by zalidthebur** [comment]
@niketa-wow All looks good to me now :-)

**Comment by zalidthebur** [comment]
@selenara I suspect you opened the file in a word processor. You need to open it in a spreadsheet program with comma separator selected. Hope that helps ;-)

**Comment by niketa-wow** [comment]
> @selenara I suspect you opened the file in a word processor. You need to open it in a spreadsheet program with comma separator selected. Hope that helps ;-)

@zalidthebur were you able to export and read a file ok? I'm worried that the output he gave doesn't even show commas or semicolons. Would they be stripped if a csv is opened in word, etc?

**Comment by zalidthebur** [comment]
@niketa-wow Yeah. Works in a spreadsheet as I replied to Selenara. No idea why there are no commas in his/hers.

**Comment by zalidthebur** [comment]
@niketa-wow Just tried it in a Word Processor (LibreOffice Writer) and the commas are there : 
guildName,snapshotDate,tabName,transactionType,name,itemName,itemLevel,itemMoneyCount,moveTabName1,moveTabName2,timeSince,transactionDate,line
XXXXX-Steamwheedle Cartel [H],Jul 23, 2021 (20:09),Pets Bags etc,withdraw,XXXXXX,Pet Cage,,1,,,2 days ago,approx. 8 PM on 7/21/21,XXXXXX withdrew [Pet Cage]   at approx. 8 PM on 7/21/21
XXXXX-Steamwheedle Cartel [H],Jul 23, 2021 (20:09),Pets Bags etc,withdraw,XXXXXX,Pet Cage,,1,,,3 days ago,approx. 11 PM on 7/20/21,XXXX withdrew [Pet Cage]   at approx. 11 PM on 7/20/21

**Comment by niketa-wow** [comment]
@selenara can you attach the CSV file itself and a copy of your saved variables?

**Comment by niketa-wow** [comment]
@selenara another thought, did you add 

or ","

Or did you add

or ""

Because it's possible you forgot to add the comma when you changed the lines

**Comment by selenara** [comment]
local delimiter = db.settings.exportDelimiter or "," 
That's what I added in Manage.lua

I don't know where the stored variables are.
I opened the file in windows 10 notepad and it shows like this. I saved the .csv file with windows notepad.
I tried to open it with excel 2010 and it looks the same like the notepad file (I don't know how to put comma separator)

[test.zip](https://github.com/niketa-wow/guildbanksnapshots/files/6871596/test.zip)

**Comment by niketa-wow** [comment]
> local delimiter = db.settings.exportDelimiter or "," 
> 
> That's what I added in Manage.lua
> 
> 
> 
> I don't know where the stored variables are.
> 
> I opened the file in windows 10 notepad and it shows like this. I saved the .csv file with windows notepad.
> 
> I tried to open it with excel 2010 and it looks the same like the notepad file (I don't know how to put comma separator)
> 
> 
> 
> [test.zip](https://github.com/niketa-wow/guildbanksnapshots/files/6871596/test.zip)
> 
> 

Go to the folder WoW is installed in> WTF > Account > your account name / number > SavedVariables > GuildBankSnapshots.lua

Alternatively type this and tell me what it says

/run print(GuildBankSnapshotsDB.settings.exportDelimiter, GuildBankSnapshotsDB.settings.dateFormat)

**Comment by selenara** [comment]
[GuildBankSnapshots.zip](https://github.com/niketa-wow/guildbanksnapshots/files/6871629/GuildBankSnapshots.zip)

**Comment by niketa-wow** [comment]
@selenara 

I've found the issue. Please run the command:

/run GuildBankSnapshotsDB.settings.exportDelimiter = ","

Or change the comma to a semicolon if you'd rather use that. You should be able export properly then.

Do not change this in settings until I push an update as changing the delimiter from the settings menu will recorrupt your saved variables.

I need to wait until I get home to do this fix so I can automatically fix corrupt DBs for anyone else having this issue, so slightly too much to do on my phone without testing.

**Comment by selenara** [comment]
It all works now.

Thank you very much for your support. You were very kind, patient and helpful. I enjoy this addon because in my guild I am responsible with maintaining the vault (for consumables). I use the logs to make statistics using Microsoft Access.

**Comment by niketa-wow** [comment]
No problem at all. Thanks for your patience as well. I dropped the ball on this update. Was busy and pushed a user contribution without thoroughly testing after a quick glance. Then the next fix was a quick fix before raid. Lesson learned. ><
