### ISSUE TITLE
[BUG] error message "please open your guild bank and try again."

### ISSUE THREAD

**Issue by Poisonenvy2** [nikkisaurus/GuildBankSnapshots#6]
**Describe the bug**
No longer auto-snapshots.  Will not take a snapshot manually, giving the error in the heading.

lua error in bugsack:

2x Interface/AddOns/GuildBankSnapshots/GUI.lua:90: bad argument #1 to 'Click' (Usage: self:Click([button, isDown]))
[string "=[C]"]: in function `Click'
[string "@Interface/AddOns/GuildBankSnapshots/GUI.lua"]:90: in function `CreateFrame'
[string "@Interface/AddOns/GuildBankSnapshots/Core.lua"]:54: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5219: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4883: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4919: in function <Interface/FrameXML/ChatFrame.lua:4915>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
(*temporary) = GuildBankSnapshotsSnapshotsTabBTN {
 0 = <userdata>
}
(*temporary) = GuildBankSnapshotsFrame {
 0 = <userdata>
 ScanBank = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:350
 GetFormattedGuildName = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:261
 ExportPendingBTN = GuildBankSnapshotsExportPendingBTN {
 }
 exportDelimiterDropDown = Button {
 }
 GetMoneyString = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:266
 tabFrames = <table> {
 }
 CreateSettingsTab = <function> defined @Interface/AddOns/GuildBankSnapshots/Settings.lua:9
 pendingExportsScrollFrame = GuildBankSnapshotsSnapshotScrollFrame {
 }
 TopBorder = Texture {
 }
 LoadPendingSnapshotsList = <function> defined @Interface/AddOns/GuildBankSnapshots/Manage.lua:428
 TitleBg = Texture {
 }
 GUILDBANKFRAME_CLOSED = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:210
 resetExportsBTN = GuildBankSnapshotsResetExportsBTN {
 }
 BotRightCorner = Texture {
 }
 count = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:60
 RightBorder = Texture {
 }
 LoadSnapshot = <function> defined @Interface/AddOns/GuildBankSnapshots/Snapshots.lua:237
 GetElapsedTime = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:236
 pairsByKeys = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:73
 TopRightCorner = Texture {
 }
 Bg = Texture {
 }
 tabDropDownButton = GuildBankSnapshotsTabDropDownButton {
 }
 exportScrollFrame = GuildBankSnapshotsSnapshotScrollFrame {
 }
 exportEditbox = GuildBankSnapshotsExportSnapshotsEditbox {
 }
 selectAllSnapshotsBTN = GuildBankSnapshotsSelectAllSnapshotsBTN {
 }
 filterDropDownButton = GuildBankSnapshotsFilterDropDownButton {
 }
 TitleText = FontString {
 }
 DeleteActiveGuildBTN = GuildBankSnapshotsDeleteActiveGuildBTN {
 }
 CreateSnapshotsTab = <function> defined @Interface/AddOns/GuildBankSnapshots/Snapshots.lua:9
 guildExportDropDownButton = GuildBankSnapshotsGuildExportDropDownButton {
 }
 snapshotExportScrollFrame = GuildBankSnapshotsSnapshotScrollFrame {
 }
 snapshotScrollFrame = GuildBankSnapshotsSnapshotScrollFrame {
 }
 TopLeftCorner = Texture {
 }
 Delete = <function> defined @Interface/AddOns/GuildBankSnapshots/Manage.lua:358
 UpdateFrame = <function> defined @Interface/AddOns/GuildBankSnapshots/GUI.lua:140
 defaultGuildDropDown = Button {
 }
 transactionsScrollFrame = GuildBankSnapshotsTransactionsScrollFrame {
 }
 removeAllSnapshotsBTN = GuildBankSnapshotsRemoveAllSnapshotsBTN {
 }
 snapshotBTNs = <table> {
 }
 guild = "G:Dark|sWolves:H:Lightbringer"
 LeftBorder = Texture {
 }
 exportGuild = "G:Dark|sWolves:H:Lightbringer"
 GetGuildID = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:216
 CreateHelpTab = <function> defined @Interface/AddOns/GuildBankSnapshots/Help.lua:9
 copySnapshotBTN = GuildBankSnapshotsCopySnapshotBTN {
 }
 GetFormattedDate = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:257
 print = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:95
 ExportAllBTN = GuildBankSnapshotsExportAllBTN {
 }
 FilterDropDownButton_Initialization = <function> defined @Interface/AddOns/GuildBankSnapshots/Filter.lua:9
 GUILDBANKFRAME_OPENED = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:184
 GetDate = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:221
 DeleteActiveSnapshotBTN = GuildBankSnapshotsDeleteActiveSnapshotBTN {
 }
 round = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:69
 ExportPending = <function> defined @Interface/AddOns/GuildBankSnapshots/Manage.lua:378
 DeleteAllSnapshotsBTN = GuildBankSnapshotsDeleteAllSnapshotsBTN {
 }
 sortSnapshotBTN = GuildBankSnapshotsSortSnapshotBTN {
 }
 TopTileStreaks = Texture {
 }
 CreateScrollFrame = <function> defined @Interface/AddOns/GuildBankSnapshots/GUI.lua:105
 FormatLine = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:280
 ADDON_LOADED = <function> defined @Interface/AddOns/GuildBankSnapshots/Core.lua:102
 guildDropDownButton = GuildBankSnapsho

**Client**
Retail 10.0. GBS version v2.0.9

**To Reproduce**
see above

**Expected behavior**
Autosnapshots or, at the very least, the ability to manually snapshot.

**Comment by nikkisaurus** [comment]
v2.x.x is no longer supported. I am working on a beta version, but I will push it as a release so others don't have this issue.
