### ISSUE TITLE
[BUG] Latest 10.0 update Lua Error

### ISSUE THREAD

**Issue by zalidthebur** [nikkisaurus/GuildBankSnapshots#7]
Date: 2022-10-29 23:03:24
ID: 3
Error occured in: Global
Count: 1
Message: ...erface/AddOns/GuildBankSnapshots/Modules/Helpers.lua line 12:
   attempt to index local 'scan' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/GuildBankSnapshots/Modules/Helpers.lua"]:12: GetFilterNames()
   [string "@Interface/AddOns/GuildBankSnapshots/Modules/Review.lua"]:91:
      ...terface/AddOns/GuildBankSnapshots/Modules/Review.lua:86
   [string "@Interface/AddOns/GuildBankSnapshots/Modules/Review.lua"]:189:
      ...terface/AddOns/GuildBankSnapshots/Modules/Review.lua:184
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66:
      Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: Fire()
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:342: SelectTab()
   [string "@Interface/AddOns/GuildBankSnapshots/Modules/Review.lua"]:204:
      ...terface/AddOns/GuildBankSnapshots/Modules/Review.lua:195
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66:
      Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: Fire()
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua"]:522: Select()
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua"]:526: SelectByPath()
   [string "@Interface/AddOns/GuildBankSnapshots/Modules/Review.lua"]:222:
      ...terface/AddOns/GuildBankSnapshots/Modules/Review.lua:207
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66:
      Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: Fire()
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/widgets/AceGUIContainer-DropDownGroup.lua"]:66: SetGroup()
   [string "@Interface/AddOns/GuildBankSnapshots/Modules/Review.lua"]:233: ?()
   [string "@Interface/AddOns/GuildBankSnapshots/Modules/Frame.lua"]:44:
      ...nterface/AddOns/GuildBankSnapshots/Modules/Frame.lua:42
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66:
      Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: Fire()
   [string "@Interface/AddOns/Ace3/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:342: SelectTab()
   [string "@Interface/AddOns/GuildBankSnapshots/Modules/Frame.lua"]:47: InitializeFrame()
   [string "@Interface/AddOns/GuildBankSnapshots/GuildBankSnapshots.lua"]:17:
      ...ace/AddOns/GuildBankSnapshots/GuildBankSnapshots.lua:14
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66:
      Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:494: InitializeAddon()
   [string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:619:
      Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611
Locals:
None
AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  WowheadLooter, v100000
  Ace3, vRelease-r1294
  AchievementsReminder, v
  AckisRecipeList, v9.2.0
  AckisRecipeListQuickScan, v7.3.0.1
  ACP, v3.5.7-5-g619b778 
  AddonFactory, v9.2.006
  AdiBags, vv1.9.46
  AdvancedInterfaceOptions, v1.8.1
  AllTheThings, vDF-3.0.1
  Altoholic, v9.2.006
  AskMrRobot, v114
  Auctionator, v10.0.3
  BadBoy, vv10.0.0
  BarrelsOEasy, v1.2.02
  BattlePetDailyTamer, v3.2.1
  BattlePetBattleUITweaks, v2.1.3
  BattlePetBreedID, vv1.22.1
  BtWObjectiveFilter, v1.3
  BtWQuests, v2.22.0
  BtWQuestsBattleForAzeroth, v53.14
  BtWQuestsBattleForAzerothPrologue, v15.6
  BtWQuestsShadowlands, v6.4
  BtWQuestsShadowlandsPrologue, v1.8
  BuyEmAll, v3.5.12
  CanIMogIt, v10.0.0v1.35
  ClassTimer, v2.4.90001.1
  Collectionator, v0.97
  CollectMe, v2.11
  ConfirmSP, v0.21.07.06
  CovenantAbilityChanger, v1.10.1
  DataStore, v2022.10.25
  DataStoreAchievements, v9.2.004
  DataStoreAgenda, v9.2.004
  DataStoreAuctions, v9.2.004
  DataStoreCharacters, v2022.10.25
  DataStoreContainers, v9.2.004
  DataStoreCrafts, v9.2.004
  DataStoreCurrencies, v9.2.004
  DataStoreGarrisons, v9.2.004
  DataStoreInventory, v9.2.004
  DataStoreMails, v2022.10.25
  DataStorePets, v9.2.004
  DataStoreQuests, v9.2.004
  DataStoreReputations, v9.2.004
  DataStoreSpells, v2022.10.25
  DataStoreStats, v9.2.004
  DataStoreTalents, v9.2.004
  DBMCore, v25a28fd
  DBMStatusBarTimers, v25a28fd
  DBMVPVEM, v47b3faf
  DeathAlerts, v1.2
  Decursive, v2.7.8.11
  DejaCharacterStats, vR100000r1
  Dejunk, v1.3.1
  Details, v#Details.DF.Wrath.10205.146
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyDelete, v9.0.1
  FamilyFamiliarHelper, v2.0.1
  FocusHealthPercent, v4.0.1
  GTFO, v4.69.1
  GuildBankSnapshots, vv3.1.2
  TomTom, vv3.3.1-release
  BlizRuntimeLib_enUS v10.0.0.100000 <none>
  (ck=772)

**Comment by Poisonenvy2** [comment]
Yes I've come across the same issue.  The addon says it's doing a snapshot, but nothing shows up in review tab until I pick a date .. and there is no longer any history - so I only have today's snapshot (I do like the new interface and filter options though!)

After that all sorts of weird stuff happens .. blank screens and then, on close, random empty drop down boxes left on the screen.

**Comment by nikkisaurus** [comment]
@zalidthebur What steps did you take before running into this error?
@Poisonenvy2 Did you receive the same error? Or do you have additional errors to post?

**Comment by Poisonenvy2** [comment]
I believe mine is the same error.  It shows up in bugsack as soon as I log in.  I'll post here though, just in case it's not the same:

4x ...erface/AddOns/GuildBankSnapshots/Modules/Helpers.lua:12: attempt to index local 'scan' (a nil value)
[string "@Interface/AddOns/GuildBankSnapshots/Modules/Helpers.lua"]:12: in function `GetFilterNames'
[string "@Interface/AddOns/GuildBankSnapshots/Modules/Review.lua"]:91: in function <...terface/AddOns/GuildBankSnapshots/Modules/Review.lua:86>
[string "@Interface/AddOns/GuildBankSnapshots/Modules/Review.lua"]:189: in function <...terface/AddOns/GuildBankSnapshots/Modules/Review.lua:184>
[string "=[C]"]: ?
[string "@Interface/AddOns/GuildBankSnapshots/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...ns/GuildBankSnapshots/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/GuildBankSnapshots/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/GuildBankSnapshots/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Interface/AddOns/GuildBankSnapshots/Modules/Review.lua"]:204: in function <...terface/AddOns/GuildBankSnapshots/Modules/Review.lua:195>
[string "=[C]"]: ?
[string "@Interface/AddOns/GuildBankSnapshots/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...ns/GuildBankSnapshots/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/GuildBankSnapshots/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/GuildBankSnapshots/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:522: in function `Select'
...
[string "=[C]"]: ?
[string "@Interface/AddOns/GuildBankSnapshots/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...ns/GuildBankSnapshots/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/GuildBankSnapshots/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/GuildBankSnapshots/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Interface/AddOns/GuildBankSnapshots/Modules/Frame.lua"]:47: in function `InitializeFrame'
[string "@Interface/AddOns/GuildBankSnapshots/GuildBankSnapshots.lua"]:17: in function <...ace/AddOns/GuildBankSnapshots/GuildBankSnapshots.lua:14>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:623: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>

**Comment by nikkisaurus** [comment]
Try v3.2.0 and let me know if the error persists.

**Comment by Poisonenvy2** [comment]
Yes that seems to have fixed that error.  But I seem to have come across another one now .. I'll open a new one for that though.

**Comment by zalidthebur** [comment]
Was same as Poisonenvy 2 in that it popped up on login. It's gone now so will close issue. Thanks.
